unsigned long time_1 = 0;

void playwave(int pin, float frequency, int duration){
  if (frequency==0){
        analogWrite(pin, 2046);
    delay(duration);
    return;
  }
    float resolution = 40; // affects tone frequency
    float periodDuration = 1/frequency;
    float amplDelay = periodDuration/resolution;
    float amplDelay_ms = amplDelay*1000000;
    //
    time_1 = millis();
    do {
    //analogWrite(A0, 2047);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 2207);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 2367);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 2524);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 2679);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 2830);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 2976);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 3116);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 3250);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 3376);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 3494);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 3603);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 3703);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 3792);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 3870);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 3938);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 3993);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 4037);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 4068);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 4087);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 4093);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 4087);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 4068);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 4037);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 3993);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 3938);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 3870);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 3792);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 3703);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 3603);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 3494);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 3376);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 3250);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 3116);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 2976);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 2830);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 2679);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 2524);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 2367);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 2207);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 2047);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 1886);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 1726);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 1569);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 1414);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 1263);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 1117);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 977);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 843);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 717);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 599);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 490);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 390);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 301);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 223);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 155);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 100);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 56);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 25);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 6);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 0);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 6);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 25);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 56);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 100);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 155);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 223);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 301);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 390);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 490);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 599);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 717);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 843);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 977);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 1117);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 1263);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 1414);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 1569);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 1726);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 1886);
delayMicroseconds(amplDelay_ms);
analogWrite(A0, 2046);
delayMicroseconds(amplDelay_ms);

//analogWrite(pin, 0);

    //Serial.println(millis()-time_1, 5);
    } while ((millis()-time_1) < duration);
}